#!/bin/bash

function getProgName()
{
	FULLNAME=$0
	FILENAME=${FULLNAME##*/}
	echo $FILENAME
}

if [ -t 0 ] ; then
	echo "USAGE: Please use this tool in pipe mode like: 'OTHER_CMD | $(getProgName) NUMBER'"
	echo "e.g.   'ls -l | $(getProgName) 9'"
	exit 1
fi

if [ $# != 1 ] ; then
	echo "USAGE: $(getProgName) COMMAND"
	exit 1
fi

awk '{print $'$1'}'
