#!/bin/bash

function getProgName()
{
	FULLNAME=$0
	FILENAME=${FULLNAME##*/}
	echo $FILENAME
}

PATH="."
if [ $# -gt 0 ] ; then
	PATH=$1
fi

/usr/bin/find $PATH -name .git | /usr/bin/xargs -i ~/bin/checkgit {}
