#!/bin/bash

function getProgName()
{
	FULLNAME=$0
	FILENAME=${FULLNAME##*/}
	echo $FILENAME
}

if [ $# != 2 ] ; then
	echo "USAGE: $(getProgName) DST SRC"
	echo "  mv file reversely, from param2 to param1"
	exit 1
fi

mv $2 $1
